# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Switching to Flutter dev branch
    - uses: subosito/flutter-action@v1
      with:
       channel: 'dev'

    # Enabling Flutter Web
    - run: flutter config --enable-web
    
    - run: cd /home/runner/work/ergoWeb/ergoWeb/
    # Get the latst dependencies
    - run: flutter pub get
      
    # Build our 
    - run: flutter build web --release
  
    # Using Firebase Actions to deploy to our Firebase Hosting
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.firebase_key }}
        # This is where our stored secret will come in use
